site_name: ERGOS Powershell Lab
repo_url: https://github.com/ergostechnology/Powershell_Lab
edit_uri: blob/main/docs
theme:
  name: material
  palette:
    primary: blue
    accent: green
  # Palette toggle for automatic mode
    media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode

  # Palette toggle for light mode
    media: "(prefers-color-scheme: light)"
    scheme: default 
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

  # Palette toggle for dark mode
    media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - content.action.edit
markdown_extensions:
  - smarty: {}
  - sane_lists : {}
  - footnotes: {}
  - toc:
      baselevel: 1